/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * https://lua-api.factorio.com/stable/prototypes/ItemPrototype.html
 */
export type ItemPrototype = Prototype & {
  stack_size: ItemCountType
  icons?: unknown
  icon?: FileName
  icon_size?: SpriteSizeType
  dark_background_icons?: unknown
  dark_background_icon?: FileName
  dark_background_icon_size?: SpriteSizeType
  place_result?: EntityID
  place_as_equipment_result?: EquipmentID
  fuel_category?: FuelCategoryID
  burnt_result?: ItemID
  spoil_result?: ItemID
  plant_result?: EntityID
  place_as_tile?: unknown
  pictures?: SpriteVariations
  flags?: ItemPrototypeFlags
  spoil_ticks?: Uint32
  fuel_value?: Energy
  fuel_acceleration_multiplier?: Double
  fuel_top_speed_multiplier?: Double
  fuel_emissions_multiplier?: Double
  fuel_acceleration_multiplier_quality_bonus?: Double
  fuel_top_speed_multiplier_quality_bonus?: Double
  weight?: Weight
  ingredient_to_weight_coefficient?: Double
  fuel_glow_color?: Color
  open_sound?: Sound
  close_sound?: Sound
  pick_sound?: Sound
  drop_sound?: Sound
  inventory_move_sound?: Sound
  default_import_location?: SpaceLocationID
  color_hint?: ColorHintSpecification
  has_random_tint?: Bool
  spoil_to_trigger_result?: SpoilToTriggerResult
  destroyed_by_dropping_trigger?: Trigger
  rocket_launch_products?: unknown
  send_to_orbit_mode?: SendToOrbitMode
  random_tint_color?: Color
  spoil_level?: Uint8
}
/**
 * https://lua-api.factorio.com/stable/prototypes/Prototype.html
 */
export type Prototype = PrototypeBase & {
  factoriopedia_alternative?: String
}
/**
 * https://lua-api.factorio.com/stable/types/string.html
 */
export type String = string
/**
 * https://lua-api.factorio.com/stable/types/Order.html
 */
export type Order = String
/**
 * https://lua-api.factorio.com/stable/types/ItemSubGroupID.html
 */
export type ItemSubGroupID = String
/**
 * https://lua-api.factorio.com/stable/types/bool.html
 */
export type Bool = boolean
/**
 * https://lua-api.factorio.com/stable/types/ItemCountType.html
 */
export type ItemCountType = Uint32
/**
 * https://lua-api.factorio.com/stable/types/uint32.html
 */
export type Uint32 = number
/**
 * https://lua-api.factorio.com/stable/types/FileName.html
 */
export type FileName = String
/**
 * https://lua-api.factorio.com/stable/types/SpriteSizeType.html
 */
export type SpriteSizeType = Int16
/**
 * https://lua-api.factorio.com/stable/types/int16.html
 */
export type Int16 = number
/**
 * https://lua-api.factorio.com/stable/types/EntityID.html
 */
export type EntityID = String
/**
 * https://lua-api.factorio.com/stable/types/EquipmentID.html
 */
export type EquipmentID = String
/**
 * https://lua-api.factorio.com/stable/types/FuelCategoryID.html
 */
export type FuelCategoryID = String
/**
 * https://lua-api.factorio.com/stable/types/ItemID.html
 */
export type ItemID = String
/**
 * https://lua-api.factorio.com/stable/types/Energy.html
 */
export type Energy = String
/**
 * https://lua-api.factorio.com/stable/types/double.html
 */
export type Double = number
/**
 * https://lua-api.factorio.com/stable/types/Weight.html
 */
export type Weight = Double
/**
 * https://lua-api.factorio.com/stable/types/SpaceLocationID.html
 */
export type SpaceLocationID = String
/**
 * https://lua-api.factorio.com/stable/types/SendToOrbitMode.html
 */
export type SendToOrbitMode = 'not-sendable' | 'manual' | 'automated'
/**
 * https://lua-api.factorio.com/stable/types/uint8.html
 */
export type Uint8 = number

export interface FactorioDataRaw {
  item?: {
    [k: string]: ItemPrototype
  }
}
/**
 * https://lua-api.factorio.com/stable/prototypes/PrototypeBase.html
 */
export interface PrototypeBase {
  type: String
  name: String
  order?: Order
  localised_name?: LocalisedString
  localised_description?: LocalisedString
  factoriopedia_description?: LocalisedString
  subgroup?: ItemSubGroupID
  hidden?: Bool
  hidden_in_factoriopedia?: Bool
  parameter?: Bool
  factoriopedia_simulation?: SimulationDefinition
}
/**
 * https://lua-api.factorio.com/stable/types/LocalisedString.html
 */
export interface LocalisedString {
  [k: string]: unknown
}
/**
 * https://lua-api.factorio.com/stable/types/SimulationDefinition.html
 */
export interface SimulationDefinition {
  planet?: unknown
  game_view_settings?: unknown
  save?: unknown
  init_file?: unknown
  init?: unknown
  update_file?: unknown
  update?: unknown
  mods?: unknown
  init_update_count?: unknown
  length?: unknown
  generate_map?: unknown
  checkboard?: unknown
  hide_health_bars?: unknown
  mute_technology_finished_sound?: unknown
  mute_alert_sounds?: unknown
  volume_modifier?: unknown
  override_volume?: unknown
  mute_wind_sounds?: unknown
  hide_factoriopedia_gradient?: unknown
}
/**
 * https://lua-api.factorio.com/stable/types/SpriteVariations.html
 */
export interface SpriteVariations {
  [k: string]: unknown
}
/**
 * https://lua-api.factorio.com/stable/types/ItemPrototypeFlags.html
 */
export interface ItemPrototypeFlags {
  [k: string]: unknown
}
/**
 * https://lua-api.factorio.com/stable/types/Color.html
 */
export interface Color {
  [k: string]: unknown
}
/**
 * https://lua-api.factorio.com/stable/types/Sound.html
 */
export interface Sound {
  [k: string]: unknown
}
/**
 * https://lua-api.factorio.com/stable/types/ColorHintSpecification.html
 */
export interface ColorHintSpecification {
  text?: unknown
  text_color?: unknown
}
/**
 * https://lua-api.factorio.com/stable/types/SpoilToTriggerResult.html
 */
export interface SpoilToTriggerResult {
  trigger: unknown
  items_per_trigger: unknown
}
/**
 * https://lua-api.factorio.com/stable/types/Trigger.html
 */
export interface Trigger {
  [k: string]: unknown
}
